// Lscr-107 — embedded block decompile
// scriptNumber: 7, 11 blocks
// Auto-generated by tools/decode_blocks.mjs

export function prepareMovie() {
  // block offset=0 length=152 codeLen=40
  // names: 0:Function, 1:prepareMovie
  // prologue: Function
  // prologue: prepareMovie
  // prologue: id_2
  // prologue: id_3
  // prologue: id_4
  // prologue: id_5
  // prologue: id_6
  // prologue: id_7
  // prologue: id_8
  // prologue: id_9
}

export function startMovie() {
  // block offset=152 length=1760 codeLen=255
  // names: 0:lingoXtraNoDebug, 1:lingoXtraInit, 2:_global, 3:ld, 4:String, 5:fromCharCode, 6:aid, 7:gNetID, 8:Array, 9:fileNetID, 10:lastAction, 12:mainURL, 13:http://game.nittolegends.com/, 14:gameURL, 15:gameCode1_00.aspx, 16:avatarMainURL, 17:cacheURL, 18:http://download.nittolegends.com/, 19:socketURL, 20:live.nittolegends.com, 21:uggURL, 22:http://ugg.nittolegends.com/, 23:exeName, 24:NittoLegendsBeta, 25:socketBuffer, 26:isEnc, 27:initFileHandler, 28:_system, 29:gc, 30:isIdle, 31:isConnected, 32:facebookToken, 33:facebookID, 34:facebookSessionSecret, 35:facebookSessionKey
  lingoXtraNoDebug()()
  lingoXtraInit()()
  _global
  ld = String.fromCharCode()(4)
  ?
  _global
  aid = false
  ?
  _global
  gNetID = Array()
  ?
  _global
  fileNetID = Array()
  ?
  lastAction = id_11
  ?
  mainURL = http://game.nittolegends.com/
  ?
  gameURL = (_global + gameCode1_00.aspx)
  ?
  _global
  avatarMainURL = _global.mainURL
  ?
  cacheURL = http://download.nittolegends.com/
  ?
  socketURL = live.nittolegends.com
  ?
  uggURL = http://ugg.nittolegends.com/
  ?
  exeName = NittoLegendsBeta
  ?
  socketBuffer = id_11
  ?
  _global
  isEnc = 1
  ?
  initFileHandler()()
  _system.gc()()
  _global
  isIdle = 0
  ?
  _global
  isConnected = 0
  ?
  facebookToken = id_11
  ?
  facebookID = id_11
  ?
  facebookSessionSecret = id_11
  ?
  facebookSessionKey = id_11
  ?
}

export function stopMovie() {
  // block offset=1912 length=292 codeLen=22
  // names: 0:resizeFlashSprite, 1:_global, 2:objRace, 3:RaceEngine
  resizeFlashSprite()()
  _global
  objRace = RaceEngine()
  ?
}

export function resizeWindow() {
  // block offset=2204 length=476 codeLen=66
  // names: 0:_global, 1:gMultiuserInstance, 2:ssm, 3:LO, 4:errCode, 5:setNetMessageHandler, 6:BreakConnection, 7:Rick
  _global.gMultiuserInstance
  // goto @69
  ?(LO)
  // [0x0014] op_6c
  // [0x0016] op_04
  // [0x0026] op_6d
  // [0x0028] op_04
  _global.gMultiuserInstance.setNetMessageHandler()(false, false)
  ?(Rick)
  // [0x003e] op_25
  _global
}

export function zoomWindow() {
  // block offset=2680 length=180 codeLen=8
  // names: 0:resizeFlashSprite, 1:zoomWindow
  resizeFlashSprite()()
}

export function resizeFlashSprite() {
  // block offset=2860 length=200 codeLen=8
  // names: 0:resizeFlashSprite, 1:resizeFlashSprite
  resizeFlashSprite()()
}

export function setInactive() {
  // block offset=3060 length=528 codeLen=118
  // names: 0:rect, 1:Math, 2:round, 3:_movie, 4:stage, 5:right, 6:left, 7:bottom, 8:top, 9:sprite, 10:flashSP
  // [0x0025] op_1c
  // [0x0051] op_1c
  false
  rect()
  rect = false(Math.round(), (_movie.stage.rect.right((_movie.stage.rect.left / 5767170)) * 2), Math.round(), (_movie.stage.rect.bottom((_movie.stage.rect.top / 5767170)) * 2))
  ?
  ?(flashSP)
  rect = rect
  ?
}

export function sendHeartbeat() {
  // block offset=3588 length=672 codeLen=109
  // names: 0:_global, 1:isConnected, 2:isIdle, 3:gMultiuserInstance, 4:ssm, 5:LO, 6:errCode, 7:setNetMessageHandler, 8:BreakConnection, 9:Rick, 10:sprite, 11:flashSP, 12:noActivityCB
  _global.isConnected
  // goto @112
  _global
  isIdle = 1
  ?
  _global.gMultiuserInstance
  // goto @86
  ?(LO)
  // [0x0025] op_6c
  // goto @100
  // [0x0037] op_6d
  ?.gMultiuserInstance.setNetMessageHandler()(false, false)
  // goto @140
  ?(Rick)
  // [0x004f] op_25
  // [0x0051] op_03
  _global
  ?(flashSP).noActivityCB()()
  _global
  isConnected = 0
  ?
}

export function openURL() {
  // block offset=4260 length=236 codeLen=21
  // names: 0:_global, 1:isIdle, 2:ssm, 3:H
  // [0x0006] op_20
  _global.isIdle
  // goto @24
  ?(H)
}

export function clearFB() {
  // block offset=4496 length=220 codeLen=21
  // names: 0:gotoNetPage, 1:unescape, 2:_blank
  ?(gotoNetPage(), _blank)
}

export function block_10() {
  // block offset=4716 length=380 codeLen=40
  // names: 0:_global, 1:facebookToken, 3:facebookID, 4:facebookSessionSecret, 5:facebookSessionKey
  facebookToken = id_2
  ?
  facebookID = id_2
  ?
  facebookSessionSecret = id_2
  ?
  facebookSessionKey = id_2
  ?
}
