// Lscr-102.bin-only pass-2 scaffold
// Source bins:
//   C:/Users/Dilldo/Nitto/Lingo Stuff/Lnam-100.bin
//   C:/Users/Dilldo/Nitto/Lingo Stuff/Lscr-102.bin
//
// This file preserves only what was directly decoded from the raw bin.
// It does not claim original opcode semantics or executable equivalence.

export const LSCR_102_BIN_ONLY = Object.freeze({
  scriptName: "RaceEngine",
  markers: Object.freeze({
    functionAsciiOffset: 0x01cc,
    constructorNameUtf16Offset: 0x01e0,
    prototypeScriptNameUtf16Offset: 0x0c00,
    prototypeUtf16Offset: 0x0c20,
    initUtf16Offset: 0x0c40,
    alignedTypedTableStart: 0x03e0,
    alignedTypedTableEnd: 0x0b1c,
    symbolTableStart: 0x0bf8,
    initBytecodeLengthOffset: 0x0c90,
    initBytecodeStart: 0x0c94,
    initBytecodeEndExclusive: 0x0d2a,
  }),
  standaloneTypedNames: Object.freeze([
    Object.freeze({ offset: 0x03e0, name: "sendInterval" }),
    Object.freeze({ offset: 0x0404, name: "secondBuffer" }),
    Object.freeze({ offset: 0x04dc, name: "gConvSlipB" }),
    Object.freeze({ offset: 0x0578, name: "idleRPM" }),
    Object.freeze({ offset: 0x0594, name: "tqFlyFactor" }),
    Object.freeze({ offset: 0x063c, name: "c0" }),
    Object.freeze({ offset: 0x064c, name: "c100" }),
    Object.freeze({ offset: 0x0660, name: "c1000" }),
    Object.freeze({ offset: 0x0678, name: "c10000" }),
    Object.freeze({ offset: 0x06bc, name: "c13" }),
    Object.freeze({ offset: 0x0764, name: "c9" }),
    Object.freeze({ offset: 0x0774, name: "c299" }),
    Object.freeze({ offset: 0x0788, name: "c300" }),
    Object.freeze({ offset: 0x07c0, name: "c2" }),
    Object.freeze({ offset: 0x07d0, name: "c5" }),
    Object.freeze({ offset: 0x07e0, name: "c50" }),
    Object.freeze({ offset: 0x07f4, name: "c8" }),
    Object.freeze({ offset: 0x0854, name: "c3" }),
    Object.freeze({ offset: 0x08b0, name: "c10" }),
    Object.freeze({ offset: 0x0914, name: "c200" }),
    Object.freeze({ offset: 0x0950, name: "c1320" }),
    Object.freeze({ offset: 0x0968, name: "c760" }),
    Object.freeze({ offset: 0x097c, name: "c7" }),
    Object.freeze({ offset: 0x09fc, name: "c80" }),
    Object.freeze({ offset: 0x0a60, name: "c0_2" }),
    Object.freeze({ offset: 0x0ac0, name: "c4" }),
    Object.freeze({ offset: 0x0b1c, name: "c1" }),
  ]),
  scalarRecords: Object.freeze([
    Object.freeze({ nameOffset: 0x0428, name: "DAfp", valueOffset: 0x043c, valueType: "double", value: 0.009235545 }),
    Object.freeze({ nameOffset: 0x044c, name: "g", valueOffset: 0x045c, valueType: "double", value: 32.1768 }),
    Object.freeze({ nameOffset: 0x046c, name: "rpmGearConversion", valueOffset: 0x049c, valueType: "double", value: 0.85 }),
    Object.freeze({ nameOffset: 0x04ac, name: "gConvSlipA", valueOffset: 0x04cc, valueType: "double", value: 6.28 }),
    Object.freeze({ nameOffset: 0x04fc, name: "brakeDecleration", valueOffset: 0x0528, valueType: "int32", value: -40 }),
    Object.freeze({ nameOffset: 0x0534, name: "revLimiterDeceleration", valueOffset: 0x056c, valueType: "int32", value: -30 }),
    Object.freeze({ nameOffset: 0x05b8, name: "partBreakPoint", valueOffset: 0x05e0, valueType: "double", value: 0.2 }),
    Object.freeze({ nameOffset: 0x05f0, name: "vToMph", valueOffset: 0x0608, valueType: "double", value: 0.68181818 }),
    Object.freeze({ nameOffset: 0x0618, name: "c0_5", valueOffset: 0x062c, valueType: "double", value: 0.5 }),
    Object.freeze({ nameOffset: 0x0690, name: "c0_0075", valueOffset: 0x06ac, valueType: "double", value: 0.0075 }),
    Object.freeze({ nameOffset: 0x06d0, name: "c0_4", valueOffset: 0x06e4, valueType: "double", value: 0.4 }),
    Object.freeze({ nameOffset: 0x06f4, name: "c0_7", valueOffset: 0x0708, valueType: "double", value: 0.7 }),
    Object.freeze({ nameOffset: 0x0718, name: "c1_7", valueOffset: 0x072c, valueType: "double", value: 1.7 }),
    Object.freeze({ nameOffset: 0x073c, name: "c1_25", valueOffset: 0x0754, valueType: "double", value: 1.25 }),
    Object.freeze({ nameOffset: 0x079c, name: "c5_5", valueOffset: 0x07b0, valueType: "double", value: 5.5 }),
    Object.freeze({ nameOffset: 0x0804, name: "c0_005", valueOffset: 0x081c, valueType: "double", value: 0.005 }),
    Object.freeze({ nameOffset: 0x082c, name: "c0_016", valueOffset: 0x0844, valueType: "double", value: 0.016 }),
    Object.freeze({ nameOffset: 0x0864, name: "c0_09", valueOffset: 0x087c, valueType: "double", value: 0.09 }),
    Object.freeze({ nameOffset: 0x088c, name: "c0_6", valueOffset: 0x08a0, valueType: "double", value: 0.6 }),
    Object.freeze({ nameOffset: 0x08c4, name: "c0_015", valueOffset: 0x08dc, valueType: "double", value: 0.015 }),
    Object.freeze({ nameOffset: 0x08ec, name: "c0_02", valueOffset: 0x0904, valueType: "double", value: 0.02 }),
    Object.freeze({ nameOffset: 0x0928, name: "c0_18", valueOffset: 0x0940, valueType: "double", value: 0.18 }),
    Object.freeze({ nameOffset: 0x098c, name: "c7_5", valueOffset: 0x09a0, valueType: "double", value: 7.5 }),
    Object.freeze({ nameOffset: 0x09b0, name: "c1_8", valueOffset: 0x09c4, valueType: "double", value: 1.8 }),
    Object.freeze({ nameOffset: 0x09d4, name: "c1_15", valueOffset: 0x09ec, valueType: "double", value: 1.15 }),
    Object.freeze({ nameOffset: 0x0a10, name: "c0_95", valueOffset: 0x0a28, valueType: "double", value: 0.95 }),
    Object.freeze({ nameOffset: 0x0a38, name: "c0_05", valueOffset: 0x0a50, valueType: "double", value: 0.05 }),
    Object.freeze({ nameOffset: 0x0a74, name: "c0_1", valueOffset: 0x0a88, valueType: "double", value: 0.1 }),
    Object.freeze({ nameOffset: 0x0a98, name: "c0_65", valueOffset: 0x0ab0, valueType: "double", value: 0.65 }),
    Object.freeze({ nameOffset: 0x0ad0, name: "c0_07", valueOffset: 0x0ae8, valueType: "double", value: 0.07 }),
    Object.freeze({ nameOffset: 0x0af8, name: "c2_5", valueOffset: 0x0b0c, valueType: "double", value: 2.5 }),
  ]),
  symbolTable: Object.freeze([
    Object.freeze({ offset: 0x0bf8, id: 1, type: 4, chars: 10, value: "RaceEngine" }),
    Object.freeze({ offset: 0x0c18, id: 2, type: 4, chars: 9, value: "prototype" }),
    Object.freeze({ offset: 0x0c38, id: 3, type: 4, chars: 4, value: "init" }),
  ]),
  symbolClusters: Object.freeze([
    Object.freeze({ index: 0, startOffset: 0x01e0, endOffset: 0x01e0, names: Object.freeze(["RaceEngine"]) }),
    Object.freeze({ index: 1, startOffset: 0x03ec, endOffset: 0x0410, names: Object.freeze(["sendInterval", "secondBuffer"]) }),
    Object.freeze({ index: 2, startOffset: 0x0584, endOffset: 0x05a0, names: Object.freeze(["idleRPM", "tqFlyFactor"]) }),
    Object.freeze({ index: 3, startOffset: 0x0c04, endOffset: 0x0c44, names: Object.freeze(["RaceEngine", "prototype", "init"]) }),
    Object.freeze({ index: 4, startOffset: 0x0e94, endOffset: 0x1238, names: Object.freeze(["goodCounterRT", "badCounterRT", "goodCounterET", "badCounterET", "avgFps", "fpsCount", "guid", "raceType", "timeAnchor", "staging", "stagingLightPos1", "stagingLightPos2", "greenDelay", "preStaged", "staged", "brake", "isMidMd5sent", "isNos", "turboFlow", "stockRedLine", "avgDurability", "pistonDurability", "rodDurability", "valveDurability", "headGasketDurability", "engineBlockDurability"]) }),
    Object.freeze({ index: 5, startOffset: 0x12e4, endOffset: 0x1490, names: Object.freeze(["speedoV", "engineV", "isEngineLightOn", "gearValue", "theTime", "theActualTime", "timeFromLastFrame", "timeGreen", "timeStartLine", "stagingTimeLimit"]) }),
    Object.freeze({ index: 9, startOffset: 0x1d14, endOffset: 0x2024, names: Object.freeze(["xtra", "xmlparser", "parseString", "makeList", "parseInt", "parseFloat", "stockRedLine", "redLine", "revLimiter", "detuneHp", "stockBoost", "boostSetting", "boostType", "initBoost", "Array"]) }),
    Object.freeze({ index: 10, startOffset: 0x2120, endOffset: 0x2530, names: Object.freeze(["nitrousTankSize", "setClutch", "tqArray", "turboFlow", "fuelFlowLimit", "overallAirFlowLimit", "valveNumber", "chipSetting", "rodDurability", "valveDurability", "engineBlockDurability", "oilDurability", "oilFilterDurability"]) }),
    Object.freeze({ index: 14, startOffset: 0x2d70, endOffset: 0x2f50, names: Object.freeze(["runInterval", "timeout", "sendInterval", "symbol", "sendPos", "endRace", "runInterval", "sendPos"]) }),
    Object.freeze({ index: 21, startOffset: 0x60b0, endOffset: 0x60b0, names: Object.freeze(["runEngineStageLightCB"]) }),
    Object.freeze({ index: 22, startOffset: 0x6160, endOffset: 0x61d0, names: Object.freeze(["goodCounterRT", "timeStartLine", "timeGreen", "runEngineSetLightOnCB"]) }),
    Object.freeze({ index: 23, startOffset: 0x62d8, endOffset: 0x63d4, names: Object.freeze(["RIVRT", "HTQRT", "runEngineSetMyRTCB", "badCounterET", "goodCounterET"]) }),
    Object.freeze({ index: 25, startOffset: 0x65f4, endOffset: 0x6614, names: Object.freeze(["timeAnchor", "KDONE"]) }),
    Object.freeze({ index: 26, startOffset: 0x66e0, endOffset: 0x672c, names: Object.freeze(["RIVDONE", "executeCall"]) }),
    Object.freeze({ index: 29, startOffset: 0x6f40, endOffset: 0x6fa4, names: Object.freeze(["isEngineLightOn", "runEngineDamageLightCB", "runEngineCB"]) }),
    Object.freeze({ index: 35, startOffset: 0x8a64, endOffset: 0x8bc8, names: Object.freeze(["gearValue", "carAccel", "carV", "sprite", "runEngineTractionLightCB", "engineV", "speedoV", "runEngineGearUpdateCB"]) }),
    Object.freeze({ index: 36, startOffset: 0x8db0, endOffset: 0x8f3c, names: Object.freeze(["gearValue", "staging", "carAccel", "carV", "speedoV", "engineV", "sprite", "runEngineTractionLightCB", "runEngineGearUpdateCB"]) }),
    Object.freeze({ index: 38, startOffset: 0x946c, endOffset: 0x9618, names: Object.freeze(["timeAnchor", "goodCounterRT", "badCounterRT", "goodCounterET", "badCounterET", "staging", "gearValue", "raceType", "KREADY"]) }),
    Object.freeze({ index: 39, startOffset: 0x96b8, endOffset: 0x96b8, names: Object.freeze(["RIVREADY"]) }),
    Object.freeze({ index: 41, startOffset: 0x98c0, endOffset: 0x98c0, names: Object.freeze(["HTREADY"]) }),
    Object.freeze({ index: 43, startOffset: 0x9e6c, endOffset: 0x9f28, names: Object.freeze(["stagingLightPos1", "timeout", "symbol", "secondBuffer", "stagingLightPos2"]) }),
    Object.freeze({ index: 44, startOffset: 0xa458, endOffset: 0xa618, names: Object.freeze(["stagingLightPos1", "sprite", "runEngineSetLightOnCB", "greenDelay", "timeGreen", "timeout", "symbol"]) }),
    Object.freeze({ index: 45, startOffset: 0xa6a4, endOffset: 0xa730, names: Object.freeze(["raceStartTimeCB", "stagingLightPos2", "raceType"]) }),
    Object.freeze({ index: 46, startOffset: 0xb028, endOffset: 0xb434, names: Object.freeze(["stockRedLine", "detuneHp", "stockBoost", "boostType", "boostSetting", "redLine", "revLimiter", "nitrousTankSize", "turboFlow", "fuelFlowLimit", "overallAirFlowLimit", "valveNumber", "chipSetting", "pistonDurability", "rodDurability", "valveDurability", "headGasketDurability", "engineBlockDurability", "oilDurability", "tqArray"]) }),
  ]),
  initBytecode: Object.freeze({
    length: 0x96,
    startOffset: 0x0c94,
    endOffsetExclusive: 0x0d2a,
    hex: "413e36000051413e36000151413e36000251413e36000351413e36000451413e36000551413d0007360006514154000036000851414135000a36000951414336000b51414135000a36000c51414135000a36000d51413e36000e51414236000f51414236001051414236001151414236001251414135000a360013514141350015413500161d413500171d3600145141413500194135",
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "41 3E 36 00 nn 51", count: 7 }),
      Object.freeze({ pattern: "41 42 36 00 nn 51", count: 4 }),
      Object.freeze({ pattern: "41 41 35 00 nn", count: 6 }),
      Object.freeze({ pattern: "41 35 00 nn 1D", count: 2 }),
    ]),
    motifRuns: Object.freeze([
      Object.freeze({ offset: 0x0c94, hex: "41 3e 36 00 00 51" }),
      Object.freeze({ offset: 0x0c9a, hex: "41 3e 36 00 01 51" }),
      Object.freeze({ offset: 0x0ca0, hex: "41 3e 36 00 02 51" }),
      Object.freeze({ offset: 0x0ca6, hex: "41 3e 36 00 03 51" }),
      Object.freeze({ offset: 0x0cac, hex: "41 3e 36 00 04 51" }),
      Object.freeze({ offset: 0x0cb2, hex: "41 3e 36 00 05 51" }),
      Object.freeze({ offset: 0x0ce9, hex: "41 3e 36 00 0e 51" }),
      Object.freeze({ offset: 0x0cef, hex: "41 42 36 00 0f 51" }),
      Object.freeze({ offset: 0x0cf5, hex: "41 42 36 00 10 51" }),
      Object.freeze({ offset: 0x0cfb, hex: "41 42 36 00 11 51" }),
      Object.freeze({ offset: 0x0d01, hex: "41 42 36 00 12 51" }),
      Object.freeze({ offset: 0x0cc8, hex: "41 41 35 00 0a" }),
      Object.freeze({ offset: 0x0cd7, hex: "41 41 35 00 0a" }),
      Object.freeze({ offset: 0x0ce0, hex: "41 41 35 00 0a" }),
      Object.freeze({ offset: 0x0d07, hex: "41 41 35 00 0a" }),
      Object.freeze({ offset: 0x0d10, hex: "41 41 35 00 15" }),
      Object.freeze({ offset: 0x0d23, hex: "41 41 35 00 19" }),
      Object.freeze({ offset: 0x0d15, hex: "41 35 00 16 1d" }),
      Object.freeze({ offset: 0x0d1a, hex: "41 35 00 17 1d" }),
    ]),
  }),
  postInitRegion: Object.freeze({
    startOffset: 0x0d2a,
    endOffsetExclusive: 0x0e30,
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "51 41 41 35 00 0A 36 00", count: 10 }),
      Object.freeze({ pattern: "83 27 3D 00 34 12 07 00", count: 4 }),
      Object.freeze({ pattern: "35 00 35 39 3A 00 00 51", count: 3 }),
      Object.freeze({ pattern: "51 41 3C 00 2D", count: 2 }),
    ]),
    motifRuns: Object.freeze([
      Object.freeze({ offset: 0x0dde, hex: "83 27 3d 00 34 12 07 00" }),
      Object.freeze({ offset: 0x0df4, hex: "83 27 3d 00 34 12 07 00" }),
      Object.freeze({ offset: 0x0e0e, hex: "83 27 3d 00 34 12 07 00" }),
      Object.freeze({ offset: 0x0e24, hex: "83 27 3d 00 34 12 07 00" }),
      Object.freeze({ offset: 0x0de8, hex: "35 00 35 39 3a 00 00 51" }),
      Object.freeze({ offset: 0x0dfe, hex: "35 00 35 39 3a 00 00 51" }),
      Object.freeze({ offset: 0x0e18, hex: "35 00 35 39 3a 00 00 51" }),
    ]),
  }),
  lateAlignedTable: Object.freeze({
    startOffset: 0x0e88,
    stringRunEndExclusive: 0x13d4,
    mixedTailEndExclusive: 0x1658,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x0e88, id: 0, chars: 13, value: "goodCounterRT" }),
      Object.freeze({ offset: 0x0eb0, id: 1, chars: 12, value: "badCounterRT" }),
      Object.freeze({ offset: 0x0ed4, id: 2, chars: 13, value: "goodCounterET" }),
      Object.freeze({ offset: 0x0efc, id: 3, chars: 12, value: "badCounterET" }),
      Object.freeze({ offset: 0x0f20, id: 4, chars: 6, value: "avgFps" }),
      Object.freeze({ offset: 0x0f38, id: 5, chars: 8, value: "fpsCount" }),
      Object.freeze({ offset: 0x0f54, id: 6, chars: 4, value: "guid" }),
      Object.freeze({ offset: 0x0f68, id: 7, chars: 0, value: "" }),
      Object.freeze({ offset: 0x0f74, id: 8, chars: 8, value: "raceType" }),
      Object.freeze({ offset: 0x0f90, id: 9, chars: 10, value: "timeAnchor" }),
      Object.freeze({ offset: 0x0fb0, id: 10, chars: 2, value: "c0" }),
      Object.freeze({ offset: 0x0fc0, id: 11, chars: 7, value: "staging" }),
      Object.freeze({ offset: 0x0fdc, id: 12, chars: 16, value: "stagingLightPos1" }),
      Object.freeze({ offset: 0x1008, id: 13, chars: 16, value: "stagingLightPos2" }),
      Object.freeze({ offset: 0x1034, id: 14, chars: 10, value: "greenDelay" }),
      Object.freeze({ offset: 0x1054, id: 15, chars: 9, value: "preStaged" }),
      Object.freeze({ offset: 0x1074, id: 16, chars: 6, value: "staged" }),
      Object.freeze({ offset: 0x108c, id: 17, chars: 5, value: "brake" }),
      Object.freeze({ offset: 0x10a4, id: 18, chars: 12, value: "isMidMd5sent" }),
      Object.freeze({ offset: 0x10c8, id: 19, chars: 5, value: "isNos" }),
      Object.freeze({ offset: 0x10e0, id: 20, chars: 2, value: "pb" }),
      Object.freeze({ offset: 0x10f0, id: 21, chars: 9, value: "turboFlow" }),
      Object.freeze({ offset: 0x1110, id: 22, chars: 7, value: "c0_0075" }),
      Object.freeze({ offset: 0x112c, id: 23, chars: 12, value: "stockRedLine" }),
      Object.freeze({ offset: 0x1150, id: 24, chars: 13, value: "avgDurability" }),
      Object.freeze({ offset: 0x1178, id: 25, chars: 16, value: "pistonDurability" }),
      Object.freeze({ offset: 0x11a4, id: 26, chars: 13, value: "rodDurability" }),
      Object.freeze({ offset: 0x11cc, id: 27, chars: 15, value: "valveDurability" }),
      Object.freeze({ offset: 0x11f8, id: 28, chars: 20, value: "headGasketDurability" }),
      Object.freeze({ offset: 0x122c, id: 29, chars: 21, value: "engineBlockDurability" }),
      Object.freeze({ offset: 0x1264, id: 30, chars: 2, value: "c5" }),
      Object.freeze({ offset: 0x1274, id: 31, chars: 2, value: "hp" }),
      Object.freeze({ offset: 0x1284, id: 32, chars: 1, value: "s" }),
      Object.freeze({ offset: 0x1294, id: 33, chars: 3, value: "c13" }),
      Object.freeze({ offset: 0x12a8, id: 34, chars: 4, value: "carV" }),
      Object.freeze({ offset: 0x12bc, id: 35, chars: 8, value: "carAccel" }),
      Object.freeze({ offset: 0x12d8, id: 36, chars: 7, value: "speedoV" }),
      Object.freeze({ offset: 0x12f4, id: 37, chars: 7, value: "engineV" }),
      Object.freeze({ offset: 0x1310, id: 38, chars: 3, value: "mph" }),
      Object.freeze({ offset: 0x1324, id: 39, chars: 12, value: "engineDamage" }),
      Object.freeze({ offset: 0x1348, id: 40, chars: 15, value: "isEngineLightOn" }),
      Object.freeze({ offset: 0x1374, id: 41, chars: 9, value: "gearValue" }),
      Object.freeze({ offset: 0x1394, id: 42, chars: 2, value: "gr" }),
      Object.freeze({ offset: 0x13a4, id: 43, chars: 3, value: "grs" }),
      Object.freeze({ offset: 0x13b8, id: 44, chars: 7, value: "theTime" }),
    ]),
    mixedTailRecords: Object.freeze([
      Object.freeze({ offset: 0x13d4, id: 45, type: 2, value: 0.033 }),
      Object.freeze({ offset: 0x13e4, id: 46, type: 4, chars: 13, value: "theActualTime" }),
      Object.freeze({ offset: 0x140c, id: 47, type: 4, chars: 17, value: "timeFromLastFrame" }),
      Object.freeze({ offset: 0x143c, id: 48, type: 4, chars: 9, value: "timeGreen" }),
      Object.freeze({ offset: 0x145c, id: 49, type: 4, chars: 13, value: "timeStartLine" }),
      Object.freeze({ offset: 0x1484, id: 50, type: 4, chars: 16, value: "stagingTimeLimit" }),
      Object.freeze({ offset: 0x14b0, id: 51, type: 4, chars: 12, value: "lightDelayTO" }),
      Object.freeze({ offset: 0x14d4, id: 52, type: 4, chars: 6, value: "object" }),
      Object.freeze({ offset: 0x14ec, id: 53, type: 4, chars: 6, value: "forget" }),
      Object.freeze({ offset: 0x1504, id: 54, type: 4, chars: 8, value: "lightTO1" }),
      Object.freeze({ offset: 0x1520, id: 55, type: 4, chars: 8, value: "lightTO2" }),
      Object.freeze({ offset: 0x153c, id: 56, type: 4, chars: 11, value: "runInterval" }),
      Object.freeze({ offset: 0x1560, id: 57, type: 4, chars: 2, value: "rt" }),
      Object.freeze({ offset: 0x1570, id: 58, type: 4, chars: 9, value: "undefined" }),
      Object.freeze({ offset: 0x1590, id: 59, type: 4, chars: 2, value: "et" }),
      Object.freeze({ offset: 0x15a0, id: 60, type: 4, chars: 2, value: "ts" }),
      Object.freeze({ offset: 0x15b0, id: 61, type: 4, chars: 2, value: "bt" }),
      Object.freeze({ offset: 0x15c0, id: 62, type: 4, chars: 4, value: "slip" }),
      Object.freeze({ offset: 0x15d4, id: 63, type: 4, chars: 3, value: "rpm" }),
      Object.freeze({ offset: 0x15e8, id: 64, type: 4, chars: 7, value: "idleRPM" }),
      Object.freeze({ offset: 0x1604, id: 65, type: 4, chars: 1, value: "N" }),
      Object.freeze({ offset: 0x1614, id: 66, type: 4, chars: 1, value: "w" }),
      Object.freeze({ offset: 0x1624, id: 67, type: 4, chars: 4, value: "c0_4" }),
      Object.freeze({ offset: 0x1638, id: 68, type: 4, chars: 9, value: "getTorque" }),
    ]),
  }),
  rawBlock1658: Object.freeze({
    startOffset: 0x1658,
    endOffsetExclusive: 0x1750,
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "b4 62 01 63 05 b4", count: 16 }),
      Object.freeze({ pattern: "62 01 63 05 b4 62", count: 15 }),
      Object.freeze({ pattern: "62 02 b4 62 02 b4", count: 8 }),
      Object.freeze({ pattern: "64 04 b4 64 04 b4", count: 4 }),
      Object.freeze({ pattern: "b4 61 01 c9 08 64", count: 4 }),
    ]),
  }),
  startRaceRegion: Object.freeze({
    descriptorStartOffset: 0x1750,
    utf16NameOffset: 0x1770,
    utf16Name: "startRace",
    asciiNames: Object.freeze([
      Object.freeze({ offset: 0x17b4, value: "carXML" }),
      Object.freeze({ offset: 0x17c8, value: "torqueArray" }),
      Object.freeze({ offset: 0x17e0, value: "gParserObject" }),
      Object.freeze({ offset: 0x17fc, value: "c" }),
    ]),
    unresolvedFieldAt0x180c: 0x96,
    rawRegionStartOffset: 0x1810,
    rawRegionEndExclusive: 0x1d08,
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "56 00 01 35 00 07 35 00", count: 51 }),
      Object.freeze({ pattern: "39 56 00 01 35 00 07 35", count: 50 }),
      Object.freeze({ pattern: "3b 00 0a 39 56 00 01 35", count: 40 }),
      Object.freeze({ pattern: "51 41 3b 00 0a 39 56 00", count: 33 }),
      Object.freeze({ pattern: "51 41 3b 00 06 39 56 00", count: 10 }),
      Object.freeze({ pattern: "3a 00 01 3b 00 0a 39 56", count: 6 }),
      Object.freeze({ pattern: "3a 00 01 41 35 00 58 1e", count: 5 }),
    ]),
  }),
  table1d08: Object.freeze({
    startOffset: 0x1d08,
    endOffsetExclusive: 0x28c0,
    scalarRecords: Object.freeze([
      Object.freeze({ offset: 0x2170, id: 49, type: 2, value: 0.125 }),
    ]),
    sampleStringRecords: Object.freeze([
      Object.freeze({ offset: 0x1d08, id: 0, value: "xtra" }),
      Object.freeze({ offset: 0x1d1c, id: 1, value: "xmlparser" }),
      Object.freeze({ offset: 0x1d3c, id: 2, value: "parseString" }),
      Object.freeze({ offset: 0x1d60, id: 3, value: "makeList" }),
      Object.freeze({ offset: 0x1d9c, id: 6, value: "parseInt" }),
      Object.freeze({ offset: 0x1e00, id: 10, value: "parseFloat" }),
      Object.freeze({ offset: 0x1e30, id: 12, value: "stockRedLine" }),
      Object.freeze({ offset: 0x1e64, id: 14, value: "redLine" }),
      Object.freeze({ offset: 0x1e90, id: 16, value: "revLimiter" }),
      Object.freeze({ offset: 0x1ed0, id: 19, value: "detuneHp" }),
      Object.freeze({ offset: 0x1f50, id: 25, value: "stockBoost" }),
      Object.freeze({ offset: 0x1f80, id: 27, value: "boostSetting" }),
      Object.freeze({ offset: 0x1fb4, id: 29, value: "boostType" }),
      Object.freeze({ offset: 0x1fe4, id: 31, value: "initBoost" }),
      Object.freeze({ offset: 0x2018, id: 33, value: "Array" }),
      Object.freeze({ offset: 0x20d8, id: 44, value: "nitrousRemaining" }),
      Object.freeze({ offset: 0x2114, id: 46, value: "nitrousTankSize" }),
      Object.freeze({ offset: 0x2150, id: 48, value: "setClutch" }),
      Object.freeze({ offset: 0x2180, id: 50, value: "tqArray" }),
      Object.freeze({ offset: 0x219c, id: 51, value: "maxPsi" }),
      Object.freeze({ offset: 0x21c4, id: 53, value: "airhpi" }),
      Object.freeze({ offset: 0x21dc, id: 54, value: "turboFlow" }),
      Object.freeze({ offset: 0x220c, id: 56, value: "fuelFlowLimit" }),
      Object.freeze({ offset: 0x2244, id: 58, value: "overallAirFlowLimit" }),
      Object.freeze({ offset: 0x2288, id: 60, value: "cylinderNumber" }),
      Object.freeze({ offset: 0x22c0, id: 62, value: "valveNumber" }),
      Object.freeze({ offset: 0x22f4, id: 64, value: "pistonCompressionLevel" }),
      Object.freeze({ offset: 0x233c, id: 66, value: "chipSetting" }),
      Object.freeze({ offset: 0x2370, id: 68, value: "pistonDurability" }),
      Object.freeze({ offset: 0x23ac, id: 70, value: "rodDurability" }),
      Object.freeze({ offset: 0x23e4, id: 72, value: "valveDurability" }),
      Object.freeze({ offset: 0x2420, id: 74, value: "headGasketDurability" }),
      Object.freeze({ offset: 0x2464, id: 76, value: "engineBlockDurability" }),
      Object.freeze({ offset: 0x24ac, id: 78, value: "oilDurability" }),
      Object.freeze({ offset: 0x24e4, id: 80, value: "radiatorDurability" }),
      Object.freeze({ offset: 0x2524, id: 82, value: "oilFilterDurability" }),
      Object.freeze({ offset: 0x2568, id: 84, value: "coolantDurability" }),
      Object.freeze({ offset: 0x25a8, id: 86, value: "pistonDamage" }),
      Object.freeze({ offset: 0x25f0, id: 89, value: "partBreakPoint" }),
      Object.freeze({ offset: 0x2618, id: 90, value: "rodDamage" }),
      Object.freeze({ offset: 0x2648, id: 92, value: "valveDamage" }),
      Object.freeze({ offset: 0x267c, id: 94, value: "headGasketDamage" }),
      Object.freeze({ offset: 0x26b8, id: 96, value: "engineBlockDamage" }),
      Object.freeze({ offset: 0x26f8, id: 98, value: "oilDamage" }),
      Object.freeze({ offset: 0x2728, id: 100, value: "oilFilterDamage" }),
      Object.freeze({ offset: 0x2764, id: 102, value: "coolantDamage" }),
      Object.freeze({ offset: 0x279c, id: 104, value: "raceGas" }),
      Object.freeze({ offset: 0x27c8, id: 106, value: "tireStick" }),
      Object.freeze({ offset: 0x27f8, id: 108, value: "launchControl" }),
      Object.freeze({ offset: 0x2830, id: 110, value: "beforePistonDamage" }),
      Object.freeze({ offset: 0x2860, id: 111, value: "thePD" }),
      Object.freeze({ offset: 0x2878, id: 112, value: "theBPD" }),
      Object.freeze({ offset: 0x2890, id: 113, value: "init" }),
      Object.freeze({ offset: 0x28a4, id: 114, value: "raceType" }),
    ]),
  }),
  boostAndBeginRaceRegion: Object.freeze({
    startOffset: 0x28c0,
    endOffsetExclusive: 0x2d64,
    initBoostDescriptor: Object.freeze({
      offset: 0x2b3c,
      id: 7,
      type: 4,
      chars: 9,
      value: "initBoost",
      endOffsetExclusive: 0x2b5c,
    }),
    beginRaceDescriptor: Object.freeze({
      offset: 0x2cd0,
      id: 9,
      type: 4,
      chars: 9,
      value: "beginRace",
      endOffsetExclusive: 0x2cf0,
    }),
    cleanUtf16: Object.freeze([
      Object.freeze({ offset: 0x2b48, value: "initBoost" }),
      Object.freeze({ offset: 0x2bdc, value: "boostType" }),
      Object.freeze({ offset: 0x2c0c, value: "boostLag" }),
      Object.freeze({ offset: 0x2c28, value: "c0_7" }),
      Object.freeze({ offset: 0x2c3c, value: "boostSetting" }),
      Object.freeze({ offset: 0x2c60, value: "boostRange" }),
      Object.freeze({ offset: 0x2c80, value: "c1_7" }),
      Object.freeze({ offset: 0x2c94, value: "c0" }),
      Object.freeze({ offset: 0x2cdc, value: "beginRace" }),
    ]),
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "c8 60 03 63 06 63 0d 63", count: 38 }),
      Object.freeze({ pattern: "60 03 63 06 63 0d 63 11", count: 38 }),
      Object.freeze({ pattern: "03 63 06 63 0d 63 11 b4", count: 37 }),
      Object.freeze({ pattern: "b4 c8 60 03 63 06 63 0d", count: 34 }),
      Object.freeze({ pattern: "00 00 00 00 00 00 00 00", count: 32 }),
      Object.freeze({ pattern: "63 06 63 0d 63 11 b4 c8", count: 28 }),
      Object.freeze({ pattern: "06 63 0d 63 11 b4 c8 60", count: 28 }),
      Object.freeze({ pattern: "63 0d 63 11 b4 c8 60 03", count: 28 }),
    ]),
  }),
  table2d64: Object.freeze({
    startOffset: 0x2d64,
    endOffsetExclusive: 0x2e2c,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x2d64, id: 0, value: "runInterval" }),
      Object.freeze({ offset: 0x2d88, id: 1, value: "object" }),
      Object.freeze({ offset: 0x2da0, id: 2, value: "forget" }),
      Object.freeze({ offset: 0x2db8, id: 3, value: "timeout" }),
      Object.freeze({ offset: 0x2dd4, id: 4, value: "sendInterval" }),
      Object.freeze({ offset: 0x2df8, id: 5, value: "symbol" }),
      Object.freeze({ offset: 0x2e10, id: 6, value: "sendPos" }),
    ]),
  }),
  endRaceAndSendPosRegion: Object.freeze({
    startOffset: 0x2e2c,
    endOffsetExclusive: 0x30c8,
    endRaceDescriptor: Object.freeze({
      offset: 0x2e5c,
      id: 11,
      type: 4,
      chars: 7,
      value: "endRace",
      endOffsetExclusive: 0x2e78,
    }),
    endRaceRawBlock: Object.freeze({
      startOffset: 0x2e78,
      endOffsetExclusive: 0x2ecc,
      motifFrequencies: Object.freeze([
        Object.freeze({ pattern: "00 00 00 00 00 00 00 00", count: 12 }),
      ]),
    }),
    shortRecordCluster: Object.freeze([
      Object.freeze({ offset: 0x2ecc, id: 0, type: 4, chars: 11, value: "runInterval" }),
      Object.freeze({ offset: 0x2ef0, id: 1, type: 4, chars: 6, value: "object" }),
      Object.freeze({ offset: 0x2f08, id: 2, type: 4, chars: 6, value: "forget" }),
    ]),
    sendPosDescriptor: Object.freeze({
      offset: 0x2f44,
      id: 13,
      type: 4,
      chars: 7,
      value: "sendPos",
      endOffsetExclusive: 0x2f60,
    }),
    sendPosRawBlock: Object.freeze({
      startOffset: 0x2f60,
      endOffsetExclusive: 0x30c8,
      motifFrequencies: Object.freeze([
        Object.freeze({ pattern: "00 00 00 00 00 00 00 00", count: 12 }),
        Object.freeze({ pattern: "39 41 35 00 0b 41 35 00", count: 4 }),
        Object.freeze({ pattern: "41 35 00 0b 41 35 00 0c", count: 4 }),
        Object.freeze({ pattern: "41 35 00 03 3d 00 04 12", count: 3 }),
        Object.freeze({ pattern: "35 00 03 3d 00 04 12 44", count: 3 }),
        Object.freeze({ pattern: "00 03 3d 00 04 12 44 00", count: 3 }),
        Object.freeze({ pattern: "03 3d 00 04 12 44 00 21", count: 3 }),
        Object.freeze({ pattern: "3d 00 04 12 44 00 21 41", count: 3 }),
      ]),
    }),
  }),
  table30c8: Object.freeze({
    startOffset: 0x30c8,
    endOffsetExclusive: 0x328c,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x30c8, id: 0, value: "staging" }),
      Object.freeze({ offset: 0x30e4, id: 1, value: "rt" }),
      Object.freeze({ offset: 0x30f4, id: 2, value: "c1" }),
      Object.freeze({ offset: 0x3104, id: 3, value: "raceType" }),
      Object.freeze({ offset: 0x3120, id: 4, value: "KOTH" }),
      Object.freeze({ offset: 0x3134, id: 5, value: "RIVAL" }),
      Object.freeze({ offset: 0x314c, id: 6, value: "TEAMRIVAL" }),
      Object.freeze({ offset: 0x316c, id: 7, value: "HT" }),
      Object.freeze({ offset: 0x317c, id: 8, value: "gearValue" }),
      Object.freeze({ offset: 0x319c, id: 9, value: "c0" }),
      Object.freeze({ offset: 0x31ac, id: 10, value: "STG" }),
      Object.freeze({ offset: 0x31c0, id: 11, value: "s" }),
      Object.freeze({ offset: 0x31d0, id: 12, value: "carV" }),
      Object.freeze({ offset: 0x31e4, id: 13, value: "carAccel" }),
      Object.freeze({ offset: 0x3200, id: 14, value: "c1320" }),
      Object.freeze({ offset: 0x3218, id: 15, value: "timeAnchor" }),
      Object.freeze({ offset: 0x3238, id: 16, value: "INT" }),
      Object.freeze({ offset: 0x324c, id: 17, value: "_system" }),
      Object.freeze({ offset: 0x3268, id: 18, value: "milliseconds" }),
    ]),
    nextBoundaryOffset: 0x328c,
  }),
  mixedRegion328c: Object.freeze({
    startOffset: 0x328c,
    sampledEndOffsetExclusive: 0x3800,
    cleanUtf16: Object.freeze([
      Object.freeze({ offset: 0x332c, value: "run" }),
    ]),
    sampleAsciiNames: Object.freeze([
      Object.freeze({ offset: 0x3364, value: "throttlePercent" }),
      Object.freeze({ offset: 0x3380, value: "sDelta" }),
      Object.freeze({ offset: 0x3394, value: "totalHPI" }),
      Object.freeze({ offset: 0x33a8, value: "availableNitrousPower" }),
      Object.freeze({ offset: 0x33cc, value: "tqFlywheel" }),
      Object.freeze({ offset: 0x33e4, value: "tQwheel" }),
      Object.freeze({ offset: 0x33f8, value: "wheelThrust" }),
      Object.freeze({ offset: 0x3410, value: "fnd" }),
      Object.freeze({ offset: 0x3420, value: "rpmZone" }),
      Object.freeze({ offset: 0x3434, value: "extraPower" }),
      Object.freeze({ offset: 0x344c, value: "wheelThrustApplied" }),
      Object.freeze({ offset: 0x346c, value: "engineAccel" }),
      Object.freeze({ offset: 0x3484, value: "raceGasUsed" }),
      Object.freeze({ offset: 0x349c, value: "engineResistanceTPercent" }),
      Object.freeze({ offset: 0x34c0, value: "engineResistance" }),
      Object.freeze({ offset: 0x34dc, value: "carInertia" }),
      Object.freeze({ offset: 0x34f4, value: "drivetrainFnd" }),
      Object.freeze({ offset: 0x3510, value: "carFnd" }),
      Object.freeze({ offset: 0x3524, value: "mphGrip" }),
      Object.freeze({ offset: 0x3558, value: "gripIncrease" }),
      Object.freeze({ offset: 0x3570, value: "speedoAccel" }),
      Object.freeze({ offset: 0x3588, value: "vDiff" }),
      Object.freeze({ offset: 0x359c, value: "speedTween" }),
      Object.freeze({ offset: 0x35b4, value: "clutchocity" }),
      Object.freeze({ offset: 0x35cc, value: "preStaged" }),
      Object.freeze({ offset: 0x35e4, value: "staged" }),
      Object.freeze({ offset: 0x35f8, value: "rtRandom" }),
      Object.freeze({ offset: 0x360c, value: "msNow" }),
      Object.freeze({ offset: 0x36c0, value: "bPD" }),
      Object.freeze({ offset: 0x36d0, value: "adjustedBoost" }),
      Object.freeze({ offset: 0x36ec, value: "nitrousDangerLevel" }),
      Object.freeze({ offset: 0x370c, value: "tmpFlow" }),
      Object.freeze({ offset: 0x3720, value: "tmpDangerLevel" }),
      Object.freeze({ offset: 0x373c, value: "newTmpFlow" }),
      Object.freeze({ offset: 0x3754, value: "newTmpDangerLevel" }),
    ]),
    noCleanUtf16FoundFrom0x3800To0x4600: true,
  }),
  table560c: Object.freeze({
    startOffset: 0x560c,
    endOffsetExclusive: 0x5f44,
    recordCount: 86,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0x560c, id: 0, value: "c0" }),
      Object.freeze({ offset: 0x561c, id: 1, value: "c1" }),
      Object.freeze({ offset: 0x562c, id: 2, value: "timeFromLastFrame" }),
      Object.freeze({ offset: 0x565c, id: 3, value: "theTime" }),
      Object.freeze({ offset: 0x5678, id: 4, value: "_system" }),
      Object.freeze({ offset: 0x5694, id: 5, value: "milliseconds" }),
      Object.freeze({ offset: 0x56b8, id: 6, value: "c1000" }),
      Object.freeze({ offset: 0x56d0, id: 7, value: "theActualTime" }),
      Object.freeze({ offset: 0x56f8, id: 8, value: "c0_2" }),
      Object.freeze({ offset: 0x570c, id: 9, value: "avgFps" }),
      Object.freeze({ offset: 0x5724, id: 10, value: "fpsCount" }),
      Object.freeze({ offset: 0x5740, id: 11, value: "calculateExtraHpi" }),
      Object.freeze({ offset: 0x5770, id: 12, value: "carV" }),
      Object.freeze({ offset: 0x5784, id: 13, value: "c0_5" }),
      Object.freeze({ offset: 0x5798, id: 14, value: "carAccel" }),
      Object.freeze({ offset: 0x57b4, id: 15, value: "gearValue" }),
      Object.freeze({ offset: 0x57d4, id: 16, value: "hpi" }),
      Object.freeze({ offset: 0x57e8, id: 17, value: "boostCreatedPower" }),
      Object.freeze({ offset: 0x5818, id: 18, value: "systemPower" }),
      Object.freeze({ offset: 0x583c, id: 19, value: "ECUtune" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0x5dfc, id: 74, value: "UkInit" }),
      Object.freeze({ offset: 0x5e14, id: 75, value: "c3" }),
      Object.freeze({ offset: 0x5e24, id: 76, value: "c0_09" }),
      Object.freeze({ offset: 0x5e3c, id: 77, value: "c0_6" }),
      Object.freeze({ offset: 0x5e50, id: 78, value: "N" }),
      Object.freeze({ offset: 0x5e60, id: 79, value: "runEngineTractionLightCB" }),
      Object.freeze({ offset: 0x5e9c, id: 80, value: "c10" }),
      Object.freeze({ offset: 0x5eb0, id: 81, value: "tireScrub" }),
      Object.freeze({ offset: 0x5ed0, id: 82, value: "c0_015" }),
      Object.freeze({ offset: 0x5ee8, id: 83, value: "clutchFeather" }),
      Object.freeze({ offset: 0x5f10, id: 84, value: "c0_18" }),
      Object.freeze({ offset: 0x5f28, id: 85, value: "redLine" }),
    ]),
  }),
  table5f50: Object.freeze({
    startOffset: 0x5f50,
    endOffsetExclusive: 0x6fbc,
    recordCount: 142,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0x5f50, id: 87, value: "s" }),
      Object.freeze({ offset: 0x5f60, id: 88, value: "Math" }),
      Object.freeze({ offset: 0x5f74, id: 89, value: "floor" }),
      Object.freeze({ offset: 0x5f8c, id: 90, value: "staging" }),
      Object.freeze({ offset: 0x5fa8, id: 91, value: "c13" }),
      Object.freeze({ offset: 0x5fbc, id: 92, value: "preStaged" }),
      Object.freeze({ offset: 0x5fdc, id: 93, value: "staged" }),
      Object.freeze({ offset: 0x5ff4, id: 94, value: "lightDelayTO" }),
      Object.freeze({ offset: 0x6018, id: 95, value: "timeout" }),
      Object.freeze({ offset: 0x6034, id: 96, value: "symbol" }),
      Object.freeze({ offset: 0x604c, id: 97, value: "stagedAndReady" }),
      Object.freeze({ offset: 0x6074, id: 98, value: "object" }),
      Object.freeze({ offset: 0x608c, id: 99, value: "forget" }),
      Object.freeze({ offset: 0x60a4, id: 100, value: "runEngineStageLightCB" }),
      Object.freeze({ offset: 0x60dc, id: 101, value: "rt" }),
      Object.freeze({ offset: 0x60ec, id: 102, value: "undefined" }),
      Object.freeze({ offset: 0x610c, id: 103, value: "lagThreshold" }),
      Object.freeze({ offset: 0x6130, id: 104, value: "badCounterRT" }),
      Object.freeze({ offset: 0x6154, id: 105, value: "goodCounterRT" }),
      Object.freeze({ offset: 0x617c, id: 106, value: "timeStartLine" }),
      Object.freeze({ offset: 0x61a4, id: 107, value: "timeGreen" }),
      Object.freeze({ offset: 0x61c4, id: 108, value: "runEngineSetLightOnCB" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0x6ddc, id: 217, value: "valveDurability" }),
      Object.freeze({ offset: 0x6e08, id: 218, value: "valveBroken" }),
      Object.freeze({ offset: 0x6e2c, id: 219, value: "engineBlockDurability" }),
      Object.freeze({ offset: 0x6e64, id: 220, value: "engineBlockBroken" }),
      Object.freeze({ offset: 0x6e94, id: 221, value: "headGasketDurability" }),
      Object.freeze({ offset: 0x6ec8, id: 222, value: "headGasketBroken" }),
      Object.freeze({ offset: 0x6ef4, id: 223, value: "c0_4" }),
      Object.freeze({ offset: 0x6f08, id: 224, value: "c0_1" }),
      Object.freeze({ offset: 0x6f1c, id: 225, value: "c0_65" }),
      Object.freeze({ offset: 0x6f34, id: 226, value: "isEngineLightOn" }),
      Object.freeze({ offset: 0x6f60, id: 227, value: "runEngineDamageLightCB" }),
      Object.freeze({ offset: 0x6f98, id: 228, value: "runEngineCB" }),
    ]),
  }),
  rawBlock6fbc: Object.freeze({
    startOffset: 0x6fbc,
    endOffsetExclusive: 0x8074,
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "64 01 0c 64 01 b7 64 01", count: 19 }),
      Object.freeze({ pattern: "64 01 34 b4 63 03 65 01", count: 18 }),
      Object.freeze({ pattern: "01 34 b4 63 03 65 01 64", count: 18 }),
      Object.freeze({ pattern: "34 b4 63 03 65 01 64 01", count: 18 }),
      Object.freeze({ pattern: "01 0c 64 01 b7 64 01 0c", count: 18 }),
      Object.freeze({ pattern: "0c 64 01 b7 64 01 0c 64", count: 18 }),
      Object.freeze({ pattern: "64 01 b7 64 01 0c 64 01", count: 18 }),
      Object.freeze({ pattern: "01 b7 64 01 0c 64 01 b7", count: 18 }),
    ]),
  }),
  table8074: Object.freeze({
    startOffset: 0x8074,
    endOffsetExclusive: 0x84d4,
    recordCount: 39,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0x8074, id: 0, value: "rpm" }),
      Object.freeze({ offset: 0x8088, id: 1, value: "pb" }),
      Object.freeze({ offset: 0x8098, id: 2, value: "c1" }),
      Object.freeze({ offset: 0x80a8, id: 3, value: "stockBoost" }),
      Object.freeze({ offset: 0x80c8, id: 4, value: "c0" }),
      Object.freeze({ offset: 0x80d8, id: 5, value: "c1_7" }),
      Object.freeze({ offset: 0x80ec, id: 6, value: "c0_7" }),
      Object.freeze({ offset: 0x8100, id: 7, value: "boostSetting" }),
      Object.freeze({ offset: 0x8124, id: 8, value: "c7_5" }),
      Object.freeze({ offset: 0x8138, id: 9, value: "c100" }),
      Object.freeze({ offset: 0x814c, id: 10, value: "boostRange" }),
      Object.freeze({ offset: 0x816c, id: 11, value: "boostLag" }),
      Object.freeze({ offset: 0x8188, id: 12, value: "boostPsi" }),
      Object.freeze({ offset: 0x81a4, id: 13, value: "compressionPowerDelta" }),
      Object.freeze({ offset: 0x81dc, id: 14, value: "pistonCompressionLevel" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0x838c, id: 27, value: "Math" }),
      Object.freeze({ offset: 0x83a0, id: 28, value: "abs" }),
      Object.freeze({ offset: 0x83b4, id: 29, value: "engineDamageRisk" }),
      Object.freeze({ offset: 0x83e0, id: 30, value: "c0_09" }),
      Object.freeze({ offset: 0x83f8, id: 31, value: "c0_07" }),
      Object.freeze({ offset: 0x8410, id: 32, value: "c2_5" }),
      Object.freeze({ offset: 0x8424, id: 33, value: "c10" }),
      Object.freeze({ offset: 0x8438, id: 34, value: "c0_1" }),
      Object.freeze({ offset: 0x844c, id: 35, value: "ECUtune" }),
      Object.freeze({ offset: 0x8468, id: 36, value: "systemPower" }),
      Object.freeze({ offset: 0x848c, id: 37, value: "airhpi" }),
      Object.freeze({ offset: 0x84a4, id: 38, value: "boostCreatedPower" }),
    ]),
  }),
  table86f4: Object.freeze({
    startOffset: 0x86f4,
    endOffsetExclusive: 0x87ec,
    recordCount: 10,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x86f4, id: 0, value: "rpm" }),
      Object.freeze({ offset: 0x8708, id: 1, value: "undefined" }),
      Object.freeze({ offset: 0x8728, id: 2, value: "idleRPM" }),
      Object.freeze({ offset: 0x8744, id: 3, value: "c10000" }),
      Object.freeze({ offset: 0x875c, id: 4, value: "posTq" }),
      Object.freeze({ offset: 0x8774, id: 5, value: "tqArray" }),
      Object.freeze({ offset: 0x8790, id: 6, value: "parseInt" }),
      Object.freeze({ offset: 0x87ac, id: 7, value: "c100" }),
      Object.freeze({ offset: 0x87c0, id: 8, value: "negTq" }),
      Object.freeze({ offset: 0x87d8, id: 9, value: "c200" }),
    ]),
  }),
  table8a58: Object.freeze({
    startOffset: 0x8a58,
    endOffsetExclusive: 0x8bf4,
    recordCount: 15,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x8a58, id: 0, value: "gearValue" }),
      Object.freeze({ offset: 0x8a78, id: 1, value: "grs" }),
      Object.freeze({ offset: 0x8a8c, id: 2, value: "c0" }),
      Object.freeze({ offset: 0x8a9c, id: 3, value: "gr" }),
      Object.freeze({ offset: 0x8aac, id: 4, value: "mph" }),
      Object.freeze({ offset: 0x8ac0, id: 5, value: "carAccel" }),
      Object.freeze({ offset: 0x8adc, id: 6, value: "carV" }),
      Object.freeze({ offset: 0x8af0, id: 7, value: "slip" }),
      Object.freeze({ offset: 0x8b04, id: 8, value: "sprite" }),
      Object.freeze({ offset: 0x8b1c, id: 9, value: "flashSP" }),
      Object.freeze({ offset: 0x8b38, id: 10, value: "runEngineTractionLightCB" }),
      Object.freeze({ offset: 0x8b74, id: 11, value: "engineV" }),
      Object.freeze({ offset: 0x8b90, id: 12, value: "speedoV" }),
      Object.freeze({ offset: 0x8bac, id: 13, value: "hp" }),
      Object.freeze({ offset: 0x8bbc, id: 14, value: "runEngineGearUpdateCB" }),
    ]),
  }),
  table8dd0: Object.freeze({
    startOffset: 0x8dd0,
    endOffsetExclusive: 0x8f68,
    recordCount: 15,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x8dd0, id: 2, value: "staging" }),
      Object.freeze({ offset: 0x8dec, id: 3, value: "c0" }),
      Object.freeze({ offset: 0x8dfc, id: 4, value: "gr" }),
      Object.freeze({ offset: 0x8e0c, id: 5, value: "grs" }),
      Object.freeze({ offset: 0x8e20, id: 6, value: "mph" }),
      Object.freeze({ offset: 0x8e34, id: 7, value: "carAccel" }),
      Object.freeze({ offset: 0x8e50, id: 8, value: "carV" }),
      Object.freeze({ offset: 0x8e64, id: 9, value: "speedoV" }),
      Object.freeze({ offset: 0x8e80, id: 10, value: "engineV" }),
      Object.freeze({ offset: 0x8e9c, id: 11, value: "slip" }),
      Object.freeze({ offset: 0x8eb0, id: 12, value: "sprite" }),
      Object.freeze({ offset: 0x8ec8, id: 13, value: "flashSP" }),
      Object.freeze({ offset: 0x8ee4, id: 14, value: "runEngineTractionLightCB" }),
      Object.freeze({ offset: 0x8f20, id: 15, value: "hp" }),
      Object.freeze({ offset: 0x8f30, id: 16, value: "runEngineGearUpdateCB" }),
    ]),
  }),
  table9460: Object.freeze({
    startOffset: 0x9460,
    endOffsetExclusive: 0x95b8,
    recordCount: 11,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0x9460, id: 0, value: "timeAnchor" }),
      Object.freeze({ offset: 0x9480, id: 1, value: "c0" }),
      Object.freeze({ offset: 0x9490, id: 2, value: "goodCounterRT" }),
      Object.freeze({ offset: 0x94b8, id: 3, value: "badCounterRT" }),
      Object.freeze({ offset: 0x94dc, id: 4, value: "goodCounterET" }),
      Object.freeze({ offset: 0x9504, id: 5, value: "badCounterET" }),
      Object.freeze({ offset: 0x9528, id: 6, value: "lightDelayTO" }),
      Object.freeze({ offset: 0x954c, id: 7, value: "object" }),
      Object.freeze({ offset: 0x9564, id: 8, value: "forget" }),
      Object.freeze({ offset: 0x957c, id: 9, value: "staging" }),
      Object.freeze({ offset: 0x9598, id: 10, value: "gearValue" }),
    ]),
  }),
  table95c4: Object.freeze({
    startOffset: 0x95c4,
    endOffsetExclusive: 0x98d0,
    recordCount: 31,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0x95c4, id: 12, value: "gearUp" }),
      Object.freeze({ offset: 0x95dc, id: 13, value: "raceType" }),
      Object.freeze({ offset: 0x95f8, id: 14, value: "KOTH" }),
      Object.freeze({ offset: 0x960c, id: 15, value: "KREADY" }),
      Object.freeze({ offset: 0x9624, id: 16, value: "createMd5Hash" }),
      Object.freeze({ offset: 0x964c, id: 17, value: "QM" }),
      Object.freeze({ offset: 0x965c, id: 18, value: "RREADY" }),
      Object.freeze({ offset: 0x9674, id: 19, value: "RIVAL" }),
      Object.freeze({ offset: 0x968c, id: 20, value: "TEAMRIVAL" }),
      Object.freeze({ offset: 0x96ac, id: 21, value: "RIVREADY" }),
      Object.freeze({ offset: 0x96c8, id: 22, value: "CTQ" }),
      Object.freeze({ offset: 0x96dc, id: 23, value: "P" }),
      Object.freeze({ offset: 0x96ec, id: 24, value: "startLightTimer" }),
      Object.freeze({ offset: 0x9718, id: 25, value: "p" }),
      Object.freeze({ offset: 0x9728, id: 26, value: "CT" }),
      Object.freeze({ offset: 0x9738, id: 27, value: "btd" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0x979c, id: 31, value: "timeout" }),
      Object.freeze({ offset: 0x97b8, id: 32, value: "c1000" }),
      Object.freeze({ offset: 0x97d0, id: 33, value: "c2" }),
      Object.freeze({ offset: 0x97e0, id: 34, value: "symbol" }),
      Object.freeze({ offset: 0x97f8, id: 35, value: "runLight" }),
      Object.freeze({ offset: 0x9814, id: 36, value: "b" }),
      Object.freeze({ offset: 0x9824, id: 37, value: "lightTO2" }),
      Object.freeze({ offset: 0x9840, id: 38, value: "stagingLightPos2" }),
      Object.freeze({ offset: 0x986c, id: 39, value: "HTQ" }),
      Object.freeze({ offset: 0x9880, id: 40, value: "HTQREADY" }),
      Object.freeze({ offset: 0x989c, id: 41, value: "HT" }),
      Object.freeze({ offset: 0x98ac, id: 42, value: "HTREADY" }),
    ]),
  }),
  table9d04: Object.freeze({
    startOffset: 0x9d04,
    endOffsetExclusive: 0x9fd8,
    recordCount: 28,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0x9d04, id: 0, value: "greenDelay" }),
      Object.freeze({ offset: 0x9d24, id: 1, value: "parseInt" }),
      Object.freeze({ offset: 0x9d40, id: 2, value: "sprite" }),
      Object.freeze({ offset: 0x9d58, id: 3, value: "flashSP" }),
      Object.freeze({ offset: 0x9d74, id: 4, value: "setSpectateDelayCB" }),
      Object.freeze({ offset: 0x9da4, id: 5, value: "timeAnchor" }),
      Object.freeze({ offset: 0x9dc4, id: 6, value: "c0" }),
      Object.freeze({ offset: 0x9dd4, id: 7, value: "_system" }),
      Object.freeze({ offset: 0x9df0, id: 8, value: "milliseconds" }),
      Object.freeze({ offset: 0x9e14, id: 9, value: "lightTO1" }),
      Object.freeze({ offset: 0x9e30, id: 10, value: "object" }),
      Object.freeze({ offset: 0x9e48, id: 11, value: "forget" }),
      Object.freeze({ offset: 0x9e60, id: 12, value: "stagingLightPos1" }),
      Object.freeze({ offset: 0x9e8c, id: 13, value: "timeout" }),
      Object.freeze({ offset: 0x9ea8, id: 14, value: "symbol" }),
      Object.freeze({ offset: 0x9ec0, id: 15, value: "runLight" }),
      Object.freeze({ offset: 0x9edc, id: 16, value: "secondBuffer" }),
      Object.freeze({ offset: 0x9f00, id: 17, value: "lightTO2" }),
      Object.freeze({ offset: 0x9f1c, id: 18, value: "stagingLightPos2" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0x9f48, id: 19, value: "p" }),
      Object.freeze({ offset: 0x9f58, id: 20, value: "b" }),
      Object.freeze({ offset: 0x9f68, id: 21, value: "1" }),
      Object.freeze({ offset: 0x9f78, id: 22, value: "1T" }),
      Object.freeze({ offset: 0x9f88, id: 23, value: "s" }),
      Object.freeze({ offset: 0x9f98, id: 24, value: "sT" }),
      Object.freeze({ offset: 0x9fa8, id: 25, value: "o" }),
      Object.freeze({ offset: 0x9fb8, id: 26, value: "2" }),
      Object.freeze({ offset: 0x9fc8, id: 27, value: "2T" }),
    ]),
  }),
  tablea420: Object.freeze({
    startOffset: 0xa420,
    endOffsetExclusive: 0xa7dc,
    recordCount: 36,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0xa420, id: 0, value: "period" }),
      Object.freeze({ offset: 0xa438, id: 1, value: "name" }),
      Object.freeze({ offset: 0xa44c, id: 2, value: "stagingLightPos1" }),
      Object.freeze({ offset: 0xa478, id: 3, value: "c0" }),
      Object.freeze({ offset: 0xa488, id: 4, value: "sprite" }),
      Object.freeze({ offset: 0xa4a0, id: 5, value: "flashSP" }),
      Object.freeze({ offset: 0xa4bc, id: 6, value: "runEngineSetLightOnCB" }),
      Object.freeze({ offset: 0xa4f4, id: 7, value: "amber1" }),
      Object.freeze({ offset: 0xa50c, id: 8, value: "greenDelay" }),
      Object.freeze({ offset: 0xa52c, id: 9, value: "amber2" }),
      Object.freeze({ offset: 0xa544, id: 10, value: "amber3" }),
      Object.freeze({ offset: 0xa55c, id: 11, value: "forget" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0xa6f0, id: 26, value: "object" }),
      Object.freeze({ offset: 0xa708, id: 27, value: "stagingLightPos2" }),
      Object.freeze({ offset: 0xa734, id: 28, value: "raceType" }),
      Object.freeze({ offset: 0xa750, id: 29, value: "CT" }),
      Object.freeze({ offset: 0xa760, id: 30, value: "ctStartAnimateComputerCB" }),
      Object.freeze({ offset: 0xa79c, id: 31, value: "1T" }),
      Object.freeze({ offset: 0xa7ac, id: 32, value: "sT" }),
      Object.freeze({ offset: 0xa7bc, id: 33, value: "o" }),
      Object.freeze({ offset: 0xa7cc, id: 34, value: "2" }),
      Object.freeze({ offset: 0xa7dc - 16, id: 35, value: "2T" }),
    ]),
  }),
  tableb010: Object.freeze({
    startOffset: 0xb010,
    endOffsetExclusive: 0xbad0,
    recordCount: 101,
    firstRecords: Object.freeze([
      Object.freeze({ offset: 0xb010, id: 0, value: "" }),
      Object.freeze({ offset: 0xb01c, id: 1, value: "stockRedLine" }),
      Object.freeze({ offset: 0xb040, id: 2, value: "," }),
      Object.freeze({ offset: 0xb050, id: 3, value: "detuneHp" }),
      Object.freeze({ offset: 0xb06c, id: 4, value: "stockBoost" }),
      Object.freeze({ offset: 0xb08c, id: 5, value: "boostType" }),
      Object.freeze({ offset: 0xb0ac, id: 6, value: "boostSetting" }),
      Object.freeze({ offset: 0xb0d0, id: 7, value: "grs" }),
      Object.freeze({ offset: 0xb0e4, id: 8, value: "fgr" }),
      Object.freeze({ offset: 0xb0f8, id: 9, value: "redLine" }),
      Object.freeze({ offset: 0xb114, id: 10, value: "revLimiter" }),
      Object.freeze({ offset: 0xb134, id: 11, value: "UsInit" }),
    ]),
    tailRecords: Object.freeze([
      Object.freeze({ offset: 0xb988, id: 91, value: "engineDamage" }),
      Object.freeze({ offset: 0xb9ac, id: 92, value: "nogood" }),
      Object.freeze({ offset: 0xb9c4, id: 93, value: "goodCounterRT" }),
      Object.freeze({ offset: 0xb9ec, id: 94, value: "goodCounterET" }),
      Object.freeze({ offset: 0xba14, id: 95, value: "badCounterRT" }),
      Object.freeze({ offset: 0xba38, id: 96, value: "lagPercent" }),
      Object.freeze({ offset: 0xba58, id: 97, value: "badCounterET" }),
      Object.freeze({ offset: 0xba7c, id: 98, value: "xtra" }),
      Object.freeze({ offset: 0xba90, id: 99, value: "caluMD5" }),
      Object.freeze({ offset: 0xbaac, id: 100, value: "getStringMD5" }),
    ]),
  }),
  tablebda0: Object.freeze({
    startOffset: 0xbda0,
    endOffsetExclusive: 0xbe84,
    recordCount: 10,
    stringRecords: Object.freeze([
      Object.freeze({ offset: 0xbda0, id: 0, value: "Math" }),
      Object.freeze({ offset: 0xbdb4, id: 1, value: "log" }),
      Object.freeze({ offset: 0xbdc8, id: 2, value: "c1" }),
      Object.freeze({ offset: 0xbdd8, id: 3, value: "random" }),
      Object.freeze({ offset: 0xbdf0, id: 4, value: "c5" }),
      Object.freeze({ offset: 0xbe00, id: 5, value: "c0_6" }),
      Object.freeze({ offset: 0xbe14, id: 6, value: "c2" }),
      Object.freeze({ offset: 0xbe24, id: 7, value: "c0" }),
      Object.freeze({ offset: 0xbe34, id: 8, value: "round" }),
      Object.freeze({ offset: 0xbe4c, id: 9, value: "c1000" }),
    ]),
  }),
  eofTail: Object.freeze({
    fileSizeDecimal: 48988,
    fileSizeHex: 0xbf5c,
    startOffset: 0xbe84,
    endOffsetExclusive: 0xbf5c,
    motifFrequencies: Object.freeze([
      Object.freeze({ pattern: "00 00 00 00 00 00 00 00", count: 8 }),
    ]),
  }),
  cleanSymbols: Object.freeze([
    "sendInterval",
    "secondBuffer",
    "idleRPM",
    "tqFlyFactor",
    "goodCounterRT",
    "badCounterRT",
    "goodCounterET",
    "badCounterET",
    "avgFps",
    "fpsCount",
    "guid",
    "raceType",
    "timeAnchor",
    "staging",
    "stagingLightPos1",
    "stagingLightPos2",
    "greenDelay",
    "preStaged",
    "staged",
    "brake",
    "isMidMd5sent",
    "isNos",
    "turboFlow",
    "stockRedLine",
    "avgDurability",
    "pistonDurability",
    "rodDurability",
    "valveDurability",
    "headGasketDurability",
    "engineBlockDurability",
    "carV",
    "carAccel",
    "speedoV",
    "engineV",
    "mph",
    "engineDamage",
    "isEngineLightOn",
    "gearValue",
    "theTime",
    "theActualTime",
    "timeFromLastFrame",
    "timeGreen",
    "timeStartLine",
    "stagingTimeLimit",
    "runInterval",
    "getTorque",
    "startRace",
    "xtra",
    "xmlparser",
    "parseString",
    "makeList",
    "parseInt",
    "parseFloat",
    "redLine",
    "revLimiter",
    "detuneHp",
    "stockBoost",
    "boostSetting",
    "boostType",
    "boostLag",
    "boostRange",
    "initBoost",
    "beginRace",
    "Array",
    "nitrousTankSize",
    "setClutch",
    "tqArray",
    "fuelFlowLimit",
    "overallAirFlowLimit",
    "valveNumber",
    "chipSetting",
    "oilDurability",
    "radiatorDurability",
    "oilFilterDurability",
    "timeout",
    "symbol",
    "sendPos",
    "endRace",
    "KOTH",
    "RIVAL",
    "TEAMRIVAL",
    "HT",
    "INT",
    "_system",
    "milliseconds",
    "run",
    "throttlePercent",
    "sDelta",
    "totalHPI",
    "availableNitrousPower",
    "tqFlywheel",
    "tQwheel",
    "wheelThrust",
    "fnd",
    "rpmZone",
    "extraPower",
    "wheelThrustApplied",
    "engineAccel",
    "raceGasUsed",
    "engineResistanceTPercent",
    "engineResistance",
    "carInertia",
    "drivetrainFnd",
    "carFnd",
    "mphGrip",
    "gripIncrease",
    "speedoAccel",
    "vDiff",
    "speedTween",
    "clutchocity",
    "rtRandom",
    "msNow",
    "bPD",
    "adjustedBoost",
    "nitrousDangerLevel",
    "tmpFlow",
    "tmpDangerLevel",
    "newTmpFlow",
    "newTmpDangerLevel",
    "calculateExtraHpi",
    "boostCreatedPower",
    "systemPower",
    "ECUtune",
    "compressionPowerDelta",
    "Math",
    "abs",
    "floor",
    "stagedAndReady",
    "lagThreshold",
    "red",
    "KRT",
    "QM",
    "RRT",
    "runEngineNOSCB",
    "stockBoost",
    "boostPsi",
    "pistonCompressionLevel",
    "maxPsi",
    "engineDamageRisk",
    "airhpi",
    "fgr",
    "negTq",
    "g",
    "posTq",
    "UsInit",
    "UkInit",
    "tireScrub",
    "clutchFeather",
    "gearUp",
    "KREADY",
    "createMd5Hash",
    "QM",
    "RREADY",
    "CTQ",
    "CT",
    "P",
    "startLightTimer",
    "runLight",
    "HTQREADY",
    "HTREADY",
    "setSpectateDelayCB",
    "period",
    "amber1",
    "amber2",
    "amber3",
    "green",
    "raceStartTimeCB",
    "ctStartAnimateComputerCB",
    "nogood",
    "lagPercent",
    "caluMD5",
    "getStringMD5",
    "log",
    "random",
    "round",
    "sprite",
    "runEngineStageLightCB",
    "runEngineSetLightOnCB",
    "runEngineSetMyRTCB",
    "runEngineCB",
    "runEngineGearUpdateCB",
    "runEngineDamageLightCB",
    "runEngineTractionLightCB",
    "raceStartTimeCB",
    "KREADY",
    "RIVREADY",
    "HTREADY",
    "RIVRT",
    "HTQRT",
    "KDONE",
    "RIVDONE",
    "executeCall",
  ]),
});

export function RaceEngine() {}

RaceEngine.prototype.init = function init() {
  // unresolved raw init bytecode from Lscr-102.bin
  // see LSCR_102_BIN_ONLY.scalarRecords, LSCR_102_BIN_ONLY.symbolTable,
  // and LSCR_102_BIN_ONLY.initBytecode for exact recovered data.
};
